AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a pod into an Amazon EKS cluster

Resources:
  NGINXPod:
    Type: Custom::KubernetesResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:eks-cfn-resource"
      ClusterName: !Ref EKSClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      Namespace: default
      Manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: nginx-pod
        spec:
          containers:
            - name: nginx
              image: nginx

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

Parameters:
  EKSClusterName:
    Type: String
    Description: Name of the Amazon EKS cluster
