---
apiVersion: v1
kind: Namespace
metadata:
  name: tasky
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: tasky
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  labels:
    name: tasky
  namespace: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tasky
  template:
    metadata:
      labels:
        name: tasky
    spec:
      containers:
      - name: tasky
        image: marksfink/tasky:latest
        env:
          - name: MONGODB_URI
            value: mongodb://<USERNAME>:<PASSWORD>@<MONGO_EC2_DNS_NAME>:27017
          - name: SECRET_KEY
            value: <JWT_SECRET_KEY>
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tasky
  labels:
    name: tasky
  namespace: tasky
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
  - port: 50080
    targetPort: 8080
  selector:
    name: tasky
  type: LoadBalancer
